// Writes a game truck (a glTF-Transform document: one textured mesh) in the game's web-native model format, so a build
// holds nothing but ordinary static web files (some hosts accept no 3D model formats such as .glb or .fbx):
//
//   src/models/<id>.js            the mesh, node transform baked in: positions (16-bit, within the model's bounding box),
//                                 normals (16-bit), UVs (16-bit) and triangle indices as base64 typed arrays. Vite turns
//                                 each into its own lazily loaded JS chunk. (The source models are 14-bit quantized, so
//                                 nothing is lost.)
//   public/models/<id>_base.jpg   base colour
//   public/models/<id>_normal.jpg tangent-space normal map
//   public/models/<id>_mr.jpg     glTF metallic-roughness map (roughness in G, metalness in B)
//
// UVs keep the glTF convention (textures are read with flipY off), so src/vehicles/models.js rebuilds exactly the
// material GLTFLoader made from the original model.
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';

const b64 = (typed) => Buffer.from(typed.buffer, typed.byteOffset, typed.byteLength).toString('base64');
const jpeg = (img, q, data) => sharp(Buffer.from(img)).jpeg({ quality: q, chromaSubsampling: data ? '4:4:4' : '4:2:0', mozjpeg: true }).toBuffer();

/**
 * @param doc a glTF-Transform Document holding one mesh primitive (POSITION, NORMAL, TEXCOORD_0) with a
 *            metallic-roughness material
 * @param id the truck id
 * @param root the repository root
 * @returns { js, images } output paths
 */
export async function writeTruckModel(doc, id, root) {
  const meshNode = doc.getRoot().listNodes().find((n) => n.getMesh());
  if (!meshNode) throw new Error(`${id}: no mesh`);
  const prim = meshNode.getMesh().listPrimitives()[0], M = meshNode.getWorldMatrix(); // column-major
  const pos = prim.getAttribute('POSITION'), nor = prim.getAttribute('NORMAL'), uv = prim.getAttribute('TEXCOORD_0'), idx = prim.getIndices();
  const n = pos.getCount(), P = new Float32Array(n * 3), N = new Float32Array(n * 3), U = new Float32Array(n * 2), e = [0, 0, 0];
  // normals go through the inverse transpose; these models only carry translation and uniform scale, so normalising is enough
  for (let i = 0; i < n; i++) {
    pos.getElement(i, e);
    P[i * 3] = M[0] * e[0] + M[4] * e[1] + M[8] * e[2] + M[12];
    P[i * 3 + 1] = M[1] * e[0] + M[5] * e[1] + M[9] * e[2] + M[13];
    P[i * 3 + 2] = M[2] * e[0] + M[6] * e[1] + M[10] * e[2] + M[14];
    nor.getElement(i, e);
    const x = M[0] * e[0] + M[4] * e[1] + M[8] * e[2], y = M[1] * e[0] + M[5] * e[1] + M[9] * e[2], z = M[2] * e[0] + M[6] * e[1] + M[10] * e[2], l = Math.hypot(x, y, z) || 1;
    N[i * 3] = x / l; N[i * 3 + 1] = y / l; N[i * 3 + 2] = z / l;
    uv.getElement(i, e); U[i * 2] = e[0]; U[i * 2 + 1] = e[1];
  }
  // quantize: positions to the bounding box, normals to [-1, 1], UVs to their range
  const lo = [Infinity, Infinity, Infinity], hi = [-Infinity, -Infinity, -Infinity];
  for (let i = 0; i < n * 3; i++) { lo[i % 3] = Math.min(lo[i % 3], P[i]); hi[i % 3] = Math.max(hi[i % 3], P[i]); }
  const uLo = [Infinity, Infinity], uHi = [-Infinity, -Infinity];
  for (let i = 0; i < n * 2; i++) { uLo[i % 2] = Math.min(uLo[i % 2], U[i]); uHi[i % 2] = Math.max(uHi[i % 2], U[i]); }
  const qP = new Uint16Array(n * 3), qN = new Int16Array(n * 3), qU = new Uint16Array(n * 2);
  for (let i = 0; i < n * 3; i++) { const k = i % 3; qP[i] = Math.round(((P[i] - lo[k]) / ((hi[k] - lo[k]) || 1)) * 65535); qN[i] = Math.round(N[i] * 32767); }
  for (let i = 0; i < n * 2; i++) { const k = i % 2; qU[i] = Math.round(((U[i] - uLo[k]) / ((uHi[k] - uLo[k]) || 1)) * 65535); }
  const tri = idx ? idx.getArray() : Uint32Array.from({ length: n }, (_, i) => i);
  const I = n < 65536 ? Uint16Array.from(tri) : Uint32Array.from(tri);

  const mat = prim.getMaterial(), images = [];
  mkdirSync(join(root, 'public/models'), { recursive: true });
  for (const [key, tex, q, data] of [['base', mat.getBaseColorTexture(), 88, false], ['normal', mat.getNormalTexture(), 92, true], ['mr', mat.getMetallicRoughnessTexture(), 90, true]]) {
    if (!tex) continue;
    const out = join(root, 'public/models', `${id}_${key}.jpg`);
    writeFileSync(out, await jpeg(tex.getImage(), q, data)); images.push(out);
  }

  mkdirSync(join(root, 'src/models'), { recursive: true });
  const js = join(root, 'src/models', `${id}.js`);
  writeFileSync(js, `// ${id}: generated by scripts/model-writer.mjs (base64 little-endian typed arrays). Do not edit.\n` +
    `export default ${JSON.stringify({ vertices: n, index: I.BYTES_PER_ELEMENT === 2 ? 'u16' : 'u32', maps: images.map((f) => f.split('_').pop().replace('.jpg', '')),
      box: [...lo, ...hi], uvBox: [...uLo, ...uHi], position: b64(qP), normal: b64(qN), uv: b64(qU), indices: b64(I) })};\n`);
  return { js, images };
}
